export default function Home() {
  return (
   <div className="text-center p-10"> 
<h1 className="text-2xl font-bold my-4">About</h1>
<p className="text-gray-300">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero expedita facilis alias nulla quas, reiciendis distinctio harum ratione, perspiciatis vero quia accusantium, dignissimos debitis in non qui. Rem dignissimos sint aliquam. Impedit quidem illo dicta sapiente nihil aliquam deserunt quibusdam explicabo eaque at consequuntur ducimus optio, nostrum reprehenderit rem maxime ab laboriosam molestiae sint atque tempora assumenda laborum natus quod! Quidem omnis perspiciatis magnam veritatis hic qui doloribus. Facilis eum debitis dolor, quam suscipit blanditiis molestias voluptatum odit error! Voluptatibus quas iure nostrum, fugit ducimus amet aspernatur dolorem iste consectetur, optio illo pariatur culpa magni accusantium consequuntur adipisci in nemo. Impedit, blanditiis, placeat facilis, vero ducimus fugit fuga inventore rem quod unde sequi perferendis eius error mollitia sit ipsam enim doloribus doloremque adipisci sapiente! Sed repellendus soluta itaque nobis voluptatibus minima a vel pariatur beatae ipsa excepturi eum nemo deserunt ullam eaque voluptate optio, deleniti doloremque cupiditate quas perferendis distinctio inventore dolore illo. Soluta, architecto sed vel repellendus iure reprehenderit vero! Magnam esse perferendis quos praesentium fugit molestias quidem voluptatibus aut distinctio obcaecati, quis modi consequuntur quae veniam commodi accusamus ipsa repudiandae numquam autem deserunt aliquam. Voluptatem adipisci nulla aspernatur labore repellat sint cum voluptatum cupiditate nostrum ea molestiae, temporibus repudiandae, laborum accusamus eum aut ullam totam dolore dignissimos eligendi facilis perspiciatis doloribus! Numquam, at possimus consectetur maxime, doloribus quas delectus temporibus, reprehenderit perspiciatis nostrum ad dicta cupiditate vitae autem sint dolores aspernatur commodi eaque officia quo! Iure aliquam aperiam autem alias. Aliquid, non perferendis magni corrupti ad neque consequatur perspiciatis necessitatibus aperiam distinctio incidunt fugit ipsum tempore nisi explicabo ipsam ea? Veritatis fugiat, vero soluta fugit, voluptas culpa sit rem amet explicabo omnis expedita officiis rerum ullam voluptatibus iure sequi. Repudiandae maiores ipsum quam quas veritatis? Ullam sequi optio error incidunt? Praesentium quas distinctio labore earum quis quam accusantium?
</p>
   </div>
  );
}